{{- if .Values.netpol.enable }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.netpol.name }}
  namespace: {{ .Values.namespace.name | quote }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    # allow to go to WAN internet
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 172.16.0.0/20
    # or allowed to go to local namespace
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.namespace.name | lower | quote }}
  # Also
  - to:
    # allow DNS lookups
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    # on specific ports
    ports:
    - protocol: UDP
      port: 53
  {{- range .Values.netpol.allow }}
  # Also allow another overridable destination
  - to:
    - ipBlock:
        cidr: {{ . }}
  {{- end }}
{{- end }}
