apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | quote }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    app: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  # - name: https
  #   protocol: TCP
  #   port: 443
  #   targetPort: https
  type: ClusterIP
